### ISSUE TITLE
proposal: Add placeholders

### ISSUE THREAD

**Issue by Andre601** [peaceiris/actions-label-commenter#152]
**Is your feature request related to a problem? Please describe.**
From what I can tell (And what I tested so far) can you not just use something like `${{ github.event.sender.login }}` to display the name of the person opening the issue/Pull request.

**Describe the solution you'd like**
It would be nice to have some placeholders which could be used for things like the name of the person opening the issue/Pull request.

This would allow messages like `Thank you @{user} for reporting this bug!` which would be translated to `Thank you @Andre601 for reporting this bug!` and mention the user in the process.

**Describe alternatives you've considered**
There doesn't seem to be any alternatives available

**Additional context**

**Comment by peaceiris** [comment]
I have released `v1.4.0-0` and tested at #158.

https://github.com/peaceiris/actions-label-commenter/blob/82e5fadf2e9dba456b808144d2b774c5690b9afb/.github/label-commenter-config.yml#L39-L44

Could you test `v1.4.0-0`? And, do you have any ideas about another useful variable?

**Comment by Andre601** [comment]
It seems that the action is unable to even get the label-commenter-config.yml despite the fact that it does exist at the right path.

Action Error:
https://github.com/purrbot-site/PurrBot/runs/793215934?check_suite_focus=true#step:2:9

File:
https://github.com/purrbot-site/PurrBot/blob/master/.github/label-commenter-config.yml

**Comment by Andre601** [comment]
It does work.

And I at most can think of perhaps a placeholder to list asigned people for the PR/issue.
Maybe something like `{{ assignees }}` for a comma separated list of assigned people and `{{ assignees.n.login }}` for a specific one (n would be a 0 indexed number) and if nothing is there, the placeholder wouldn't be changed.
And maybe in case someone wants this `{{ assignees.mention }}` which would return the names of each assignee as a mention.

**Comment by Andre601** [comment]
I find an issue using `{{ sender.login }}`

It seems to use whoever last replied to, or performed actions on an issue/PR even if the creator of it is a different one.
For example if `ExampleUser` creates an issue and I assign a label that responds with `Hello @{{ sender.login }}` will the result be `Hello @Andre601`

**Comment by peaceiris** [comment]
`@{{ issue.user.login }}` is available now.

issue: #261
pr: #272
