### ISSUE TITLE
Doesn't work with GitHub actions/labeler@v2

### ISSUE THREAD

**Issue by tonybenchsci** [peaceiris/actions-label-commenter#210]
**Describe the bug**
We would like this (awesome, thank you) `peaceiris/actions-label-commenter` to auto-comment after auto-labelled PRs. Currently, this only works for human-added labels.

**Comment by peaceiris** [comment]
> [Authenticating with the GITHUB_TOKEN - GitHub Docs](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#using-the-github_token-in-a-workflow)
>
> When you use the repository's GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

You need to provide your personal access token to the actions/labeler.
