### ISSUE TITLE
Action failed with error: Resource not accessible by integration

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-label-commenter#24]
**Describe the bug**
Error case: [verify automated needs docs action · rapid7/metasploit-framework@7e21831](https://github.com/rapid7/metasploit-framework/runs/528655548?check_suite_focus=true#step:3:15)
See also: ["Resource not accessible by integration" · Issue #10 · actions/first-interaction](https://github.com/actions/first-interaction/issues/10)

**To Reproduce**
> This happens as soon as the person creating the PR does not have permission to the repository. I've been all day with this, and there does not seem to be a solution. Same problem as here https://github.com/actions/labeler/issues/12

**Expected behavior**
N/A

**Screenshots**
N/A

**Your YAML file**
N/A

**Additional context**
N/A

**Comment by adfoster-r7** [comment]
@peaceiris I think this Github action is great! I wonder if it's possible to turn this action into a Github App? Similar to the approach of https://github.com/kaxil/boring-cyborg

Or maybe the functionality would be good to merge into `boring-cyborg` in some way? 🤔

**Comment by peaceiris** [comment]
Thank you @adfoster-r7 for your suggestion. It sounds interesting and useful. I opened #63 and will investigate the approach.

**Comment by adfoster-r7** [comment]
Looking at the Probot documentation it seems like the event to listen to is `pull_request.labeled`. After [searching Github](https://github.com/search?q=pull_request.labeled) for this string, it seems there's similar art here too - https://github.com/dessant/label-actions

**Comment by peaceiris** [comment]
This action starts to support the `pull_request_target` event. This problem has been solved. Thanks.
