### ISSUE TITLE
Bug: sender.login is replaced with whoever added the label

### ISSUE THREAD

**Issue by Andre601** [peaceiris/actions-label-commenter#261]
**Describe the bug**
The `{{ sender.login }}` placeholder seems to get replaced with whoever was the person labeling the issue, causing stuff like mentions to mention the wrong person

**To Reproduce**
1. Use the `{{ sender.login }}` placeholder in a comment
2. Label an issue that triggers this comment

**Expected behavior**
The placeholder should instead show the actual issuer of said issue or PR (See additional context for possible solution)

**Screenshots**

**Your YAML file**
- https://github.com/PlaceholderAPI/PlaceholderAPI
- https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/.github/label-commenter-config.yml

**Additional context**
According to [Webhook events and payload](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#issues) help article is there an `issue` and `pull_request` object respectively that contains a `user` object with `login` (the name).
This seems to be the actual name of the person creating the issue while `sender.login` seems to just be whoever triggered the event.
So the action should perhaps be changed to that instead if possible.

**Comment by peaceiris** [comment]
That is my misunderstanding about `sender.login`. Thank you for reporting this.

**Comment by Andre601** [comment]
Has this been worked on? Would really like a fix for it as we use quite a few comment templates that mention the issue/pr author.

**Comment by peaceiris** [comment]
`@{{ issue.user.login }}` is available now.

Closed by #272
