### ISSUE TITLE
proposal: Add action to turn PR into Draft and vice-versa

### ISSUE THREAD

**Issue by Andre601** [peaceiris/actions-label-commenter#436]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
There should be additional actions to turn a PR into a Draft or turn a Draft into a PR.
Perhaps the `open` action could be re-used here to do draft -> PR?

**Describe alternatives you've considered**
Doing it manually... obviously.

**Additional context**
We have a specific setup for PRs in a repository, where a PR is a draft until it's ready for review and merge in which case it will receive a `Status: Ready` label, where the comment action comments about this change.
Having a way to directly change the PRs draft-status on (un)label would allow us to remove one extra step (Lazyness for the win!)

**Comment by peaceiris** [comment]
Unfortunately, the latest GitHub REST API v3 and client seem not to have the capability to change the status of `draft`.
cf. [plugin-rest-endpoint-methods.js/update.md at v5.3.1 · octokit/plugin-rest-endpoint-methods.js](https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/v5.3.1/docs/pulls/update.md)

**Comment by peaceiris** [comment]
I have opened the request. https://github.com/octokit/rest.js/issues/69

**Comment by peaceiris** [comment]
I have found the following previous requests and subscribed.

- [No way to update Pull Request Draft State - GitHub Ecosystem - GitHub Support Community](https://github.community/t/no-way-to-update-pull-request-draft-state/141890)
- [Github API: How to promote a PR from draft to ready for review? - GitHub Ecosystem - GitHub Support Community](https://github.community/t/github-api-how-to-promote-a-pr-from-draft-to-ready-for-review/177102/2)

**Comment by peaceiris** [comment]
@Andre601 Could you test the pull-request #485? For the details, see my comment on it.
