### ISSUE TITLE
support: label commenter doesn't work for discussions

### ISSUE THREAD

**Issue by JohnyP36** [peaceiris/actions-label-commenter#548]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I made a label-commenter-config.yml
But for some reason it don't work if I label a discussion. 

For example: If I label a discussion as invalid it has to comment and to lock the discussion. 
But nothing happened. With did I do wrong?

### Relevant links

```markdown
YAML config: https://github.com/JohnyP36/Connect4/blob/3fce3e5d4cf53c2c11ef1342d042bc2d529f16de/.github/label-commenter-config.yml
YAML workflow: https://github.com/JohnyP36/Connect4/blob/3fce3e5d4cf53c2c11ef1342d042bc2d529f16de/.github/workflows/label-commenter.yml
```

### Relevant log output

none

### Additional context.

I don't have set a personal access token since I thought this was not necessary with the newest version.

**Comment by peaceiris** [comment]
Please use https://github.com/peaceiris/actions-label-commenter/pull/487

**Comment by JohnyP36** [comment]
Do you mean I have to use version `@c2d00660c86f2b9ed0fb35b372c451558eba85b3` as of https://github.com/peaceiris/actions-label-commenter/pull/487#issuecomment-932675396?

**Comment by peaceiris** [comment]
yes!
